using System.Web.Http;
using Microsoft.Azure.Mobile.Server.Config;
using System.Collections.Generic;
using System.Net;
using System.Net.Http;
using System.Threading.Tasks;
using System.Security.Principal;
using Microsoft.Azure.Mobile.Server.Authentication;
using System.Linq;
using Microsoft.Azure.NotificationHubs;
using System.Web.Http.Controllers;

namespace backend.dotnet.Controllers
{
    [Authorize]
    [MobileAppController]
    public class RegisterController : ApiController
    {
        protected override void Initialize(HttpControllerContext context)
        {
            // Call the original Initialize() method
            base.Initialize(context);
        }

        [HttpPost]
        public async Task<HttpResponseMessage> Post([FromBody] RegistrationViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return new HttpResponseMessage(HttpStatusCode.BadRequest);
            }

            // We want to apply the push registration to an installation ID
            var installationId = Request.GetHeaderOrDefault("X-ZUMO-INSTALLATION-ID");
            if (installationId == null)
            {
                return new HttpResponseMessage(HttpStatusCode.BadRequest);
            }

            // Determine the right list of tasks to be handled
            List<string> validTags = new List<string>();
            foreach (string tag in model.tags)
            {
                if (tag.ToLower().Equals("news") || tag.ToLower().Equals("sports"))
                {
                    validTags.Add(tag.ToLower());
                }
            }
            // Add on the dynamic tags generated by authentication - note that the
            // [Authorize] tags means we are authenticated.
            var identity = await User.GetAppServiceIdentityAsync<AzureActiveDirectoryCredentials>(Request);
            validTags.Add($"_userid_{identity.UserId}");

            var emailClaim = identity.UserClaims.Where(c => c.Type.EndsWith("emailaddress")).FirstOrDefault();
            if (emailClaim != null)
            {
                validTags.Add($"_email_{emailClaim.Value}");
            }

            // Register with the hub
            await CreateOrUpdatePushInstallation(installationId, model.pushChannel, validTags);

            return new HttpResponseMessage(HttpStatusCode.OK);
        }

        /// <summary>
        /// Update an installation with notification hubs
        /// </summary>
        /// <param name="installationId">The installation</param>
        /// <param name="pushChannel">the GCM Push Channel</param>
        /// <param name="tags">The list of tags to register</param>
        /// <returns></returns>
        private async Task CreateOrUpdatePushInstallation(string installationId, string pushChannel, IList<string> tags)
        {
            var pushClient = Configuration.GetPushClient();

            Installation installation = new Installation
            {
                InstallationId = installationId,
                PushChannel = pushChannel,
                Tags = tags,
                Platform = NotificationPlatform.Gcm
            };
            await pushClient.CreateOrUpdateInstallationAsync(installation);
        }
    }

    /// <summary>
    /// Format of the registration view model that is passed to the custom API
    /// </summary>
    public class RegistrationViewModel
    {
        public string pushChannel;

        public List<string> tags;
    }
}
